### ISSUE TITLE
Non-applyDynamic-based Rec constructor for use with varargs

### ISSUE THREAD

**Issue by lmartel** [scala-records/scala-records#129]
I'd like to be able to manipulate the key-value tuples before creating a Rec rather than passing in literals, but [this compiler bug](https://issues.scala-lang.org/browse/SI-9308) is preventing me from accomplishing this with `Rec(tuples: _*)`.

Is there a way to create a record from a `Seq[(String, Any)]` or a `Map[String, Any]` that I'm missing, or is this use case not supported?

**Comment by vjovanov** [comment]
Depends, if you have the values for `Seq[(String, Any)]` or a `Map[String, Any]` at compile time it would be possible. However, if you need to do computations on record fields it is impossible to achieve this as the record types that are computed during type checking would only be available at runtime. 

The only way to achieve this would be to do all your computations at compile time. Scala records support only literals because they are always known at compile time. For the rest you would have to use the macros that provided by the library.

**Comment by lmartel** [comment]
That makes sense. Using a macro that calls `Macros.apply_impl` worked well for my use case, since I ended up needing to use `eval` anyway. But it might still be nice to be able to do something like:

```scala
def myRecWrapper(v: (String, Any)*): Rec[Any] = {
  println(v)
  Rec(v: _*)
}

myRecWrapper("literals" -> "like usual")
```

without needing to write a custom macro.

**Comment by vjovanov** [comment]
Yes, for something like this you would need  [`inline`](http://docs.scala-lang.org/sips/pending/inline-meta.html) which is proposed as a SIP.
